Feature/hydraboss
DanielMcCoshen/CMPT406 pull request #46
Opened 2020-03-30 23:42 UTC by ads567

2020-03-31 16:58 UTC, DanielMcCoshen requested changes
You should set the player's position correctly in the boss scene first

2020-04-01 05:34 UTC, ConnorCooke approved these changes

2020-04-03 23:21 UTC, JohannDoell approved these changes

2020-04-03 23:24 UTC, DanielMcCoshen approved these changes

2020-04-03 23:43 UTC, merged