Feature/room fixes electric boogaloo
DanielMcCoshen/CMPT406 pull request #67
Opened 2020-04-10 02:18 UTC by deeox2

2020-04-10 02:20 UTC, ConnorCooke approved these changes

2020-04-11 01:46 UTC, DanielMcCoshen requested changes

2020-04-11 01:46 UTC, DanielMcCoshen commented on Server/model/game.py
> +                        option(54, "Ice Strips", 0)
id 54? shouldnt this be 22?

2020-04-11 01:48 UTC, deeox2 commented on Server/model/game.py
> +                        option(54, "Ice Strips", 0)
Is the ID not based on entry into RoomList.cs? I always assumed it was.

2020-04-12 21:30 UTC, DanielMcCoshen commented on Server/model/game.py
> +                        option(54, "Ice Strips", 0)
Yeah my bad, assumed this was gonna be sequencial

2020-04-12 21:31 UTC, DanielMcCoshen approved these changes

2020-04-12 22:16 UTC, merged